---  
  - hosts: api2
    remote_user: root
    tasks: 
      - name:  更新api-gateway
        shell: killall java

  - hosts: api2
    remote_user: root
    tasks:
      - name:  查看进程
        shell: jps;ps -ef|grep -v grep|grep java

  - hosts: 10.0.18.165
    remote_user: root
    tasks:
      - name:  同步jar包
        shell: for i in {171..176};do rsync -aSH /usr/api-gateway.jar 10.0.18.$i:/usr/api-gateway.jar;done"

  - hosts: api2
    remote_user: root
    tasks:
      - name:  启动网关
        shell: for i in {back-center,api-gateway};do `nohup java -jar /usr/$i.jar >/dev/null 2>&1 &` sleep 1;done

  - hosts: api2
    remote_user: root
    tasks:
      - name:  查看进程
        shell: jps
